shamefullyHoist: true

packages:
  - packages/*
  - playground

catalog:
  "@nuxt/kit": ^4.2.2
  "@types/node": ^24.10.2
  "@volar/language-core": ^2.4.26
  "@volar/typescript": ^2.4.26
  "@vue/language-core": ^3.1.8
  "@vue/typescript-plugin": ^3.1.8
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.2
  chokidar: ^5.0.0
  eslint: ^9.39.1
  nuxt: ^4.2.2
  pathe: ^2.0.3
  tinyglobby: ^0.2.15
  tsdown: ^0.17.2
  typescript: ^5.9.3
  vitest: ^4.0.15
  vue: ^3.5.25
  vue-router: ^4.6.3
  zx: ^8.8.5

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
