shamefullyHoist: true

packages:
  - packages/*
  - packages/*/playground

catalog:
  "@types/node": ^24.5.2
  "@vue/language-core": ^3.0.8
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.2
  eslint: ^9.33.0
  nuxt: ^4.1.2
  tsdown: ^0.14.0
  typescript: 5.9.2
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-router: ^4.5.1
  zx: ^8.8.3

onlyBuiltDependencies:
  - esbuild
