shamefullyHoist: true

packages:
  - packages/*
  - playground

catalog:
  "@nuxt/kit": ^4.2.2
  "@types/node": ^25.0.3
  "@volar/language-core": ^2.4.27
  "@volar/typescript": ^2.4.27
  "@vscode/vsce": ^3.7.1
  "@vue/language-core": ^3.2.1
  "@vue/typescript-plugin": ^3.2.1
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/scripts": ^0.0.3
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.2
  chokidar: ^5.0.0
  eslint: ^9.39.2
  nuxt: ^4.2.2
  pathe: ^2.0.3
  tinyglobby: ^0.2.15
  tsdown: ^0.18.2
  typescript: ^5.9.3
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-router: ^4.6.4
  zx: ^8.8.5

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@vscode/vsce-sign"
  - esbuild
  - keytar
