shamefullyHoist: true

packages:
  - packages/*
  - playground

catalog:
  "@nuxt/kit": ^4.1.3
  "@types/node": ^24.7.1
  "@volar/language-core": ^2.4.23
  "@volar/typescript": ^2.4.23
  "@vue/language-core": ^3.1.1
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.1
  chokidar: ^4.0.3
  eslint: ^9.37.0
  nuxt: ^4.1.3
  pathe: 2.0.3
  tinyglobby: ^0.2.15
  tsdown: ^0.15.6
  typescript: ^5.9.3
  vue: ^3.5.22
  vue-router: ^4.5.1
  zx: ^8.8.4

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
