shamefullyHoist: true

packages:
  - packages/*
  - packages/*/playground

catalog:
  "@types/node": ^24.5.2
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.2.2
  eslint: ^9.33.0
  tsdown: ^0.14.0
  typescript: ^5.9.2
  vitest: ^3.2.4
  zx: ^8.8.3

onlyBuiltDependencies:
  - esbuild
