shamefullyHoist: true

packages:
  - packages/*
  - playground

catalog:
  "@nuxt/kit": ^4.2.1
  "@types/node": ^24.10.1
  "@volar/language-core": ^2.4.23
  "@volar/typescript": ^2.4.23
  "@vue/language-core": ^3.1.3
  "@vue/typescript-plugin": ^3.1.3
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.1
  chokidar: ^4.0.3
  eslint: ^9.39.1
  nuxt: ^4.2.1
  pathe: ^2.0.3
  tinyglobby: ^0.2.15
  tsdown: ^0.16.3
  typescript: ^5.9.3
  vitest: ^4.0.8
  vue: ^3.5.24
  vue-router: ^4.6.3
  zx: ^8.8.5

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
